# Programming Assignment 6
---
**Author:** Sheridan Payne  
**Version:** 1.0  
**Semester:** Fall 2020  

This *notebook* contains my solution to **Programming Assignment 6**

- Problem 1: 2-by-2 NumPy array operations
- Problem 2: 3-by-3 array with multiples and evenly spaced elements
- Problem 3: Loading array files and stacking

### Problem 1

In [1]:
import numpy as np

In [39]:
A = np.array([[10,20],[30,40]])
A

array([[10, 20],
       [30, 40]])

##### Part 1: Square every element of the array

In [5]:
np.square(A)

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

##### Part 2: Add 100 to every element of the array

In [6]:
A+100

array([[110, 120],
       [130, 140]])

##### Part 3: Multiply every element of the array by 5

In [7]:
5*A

array([[ 50, 100],
       [150, 200]])

##### Part 4: Calculate the square root of each element in the array

In [8]:
np.sqrt(A)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

### Problem 2

In [37]:
B = np.array(np.arange(3,28,3).reshape(3,3))
B

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [38]:
C = np.linspace(10,20,9).reshape(3,3)
C

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [20]:
B*C

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

### Problem 3

In [22]:
p1 = np.load('process1.npy')
p2 = np.load('process2.npy')
p3 = np.load('process3.npy')
p4 = np.load('process4.npy')
p5 = np.load('process5.npy')

In [31]:
D = np.vstack((p1,p2,p3,p4,p5))
D

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [36]:
D.mean(axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])